SOURCE_DIR = ..
PROJECT_CFLAGS = /WX
# Allow inline expansion of functions with an inline keyword even for debug builds
PROJECT_Debug_CFLAGS = /Ob1
# DLL-internal profiler: /DUSE_INTERNAL_PROFILER
# Time Stamp Counter profiler: /DUSE_TSC_PROFILER
# Standard Firaxis profiler (not sure if this can work w/o access to the EXE): /DFP_PROFILE_ENABLE
PROJECT_Profile_CFLAGS = /DUSE_TSC_PROFILER
PROJECT_LDFLAGS = /DEF:CvGameCoreDLL.def
PRECOMPILE_DEPENDENCIES = 
